window.people = 
	['Long beard',
	'Cell phone argument',
	'Stiletto heels',
	'Military uniform',
	'Bags under eyes',
	'Family with 3+ kids',
	'Asians with camera',
	'Cowboy hat & boots',
	'Neon-colored hair',
	'Man in a tank-top',

	'Purple shoes',
	'Couple kissing',
	'Pregnant woman',
	'Age-inappropriate clothing',
	'Too much cleavage',
	'Screaming baby',
	'Drinking coffee',
	'Barefoot',
	'Bowtie',
	'Headphones too loud',

	'College athlete',
	'Professional basketball fan',
	'Floral-print pants',
	'Booty shorts',
	'Shoulder-length earrings',
	'Man with a ponytail',
	'Dreadlocks',
	'Oxygen tank',
	'Traditional religious clothing',
	'Spray tan',

	'Overstuffed backpack or luggage',
	'Bluetooth earpiece',
	'Socks and sandals',
	'Eating on the go',
	'Redhead',
	'Obviously in a hurry',
	'Not-so-subtle gum chewer',
	'Searching bag for lost item',
	'European accent',
	'Formally dressed'

	];